name: LangSmith2Bitable Sync

on:
  schedule:
    # 工作时间（北京时间9:00-18:00）每半小时执行一次
    # 因为GitHub Actions使用UTC时间，北京时间是UTC+8
    # 所以要转换为UTC的1:00-10:00
    - cron: '0,30 1-9 * * 1-5'  # 工作日UTC 1:00-9:30，每半小时执行
    - cron: '0 10 * * 1-5'     # 工作日UTC 10:00（北京18:00）
    
    # 非工作时间每两小时执行一次
    - cron: '0 11,13,15,17,19,21,23 * * 1-5' # 工作日非工作时间，每两小时
    - cron: '0 */2 * * 0,6'    # 周末每两小时
  
  # 也支持手动触发
  workflow_dispatch:

# 添加权限配置
permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # 使用 setup-python 原生 pip 缓存
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run sync script
        run: python sync_langsmith_to_bitable.py
        env:
          LS_API_KEY: ${{ secrets.LS_API_KEY }}
          APP_ID: ${{ secrets.APP_ID }}
          APP_SECRET: ${{ secrets.APP_SECRET }}

      - name: Commit and push changes
        if: success()
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add state.json local_records.json
          git diff --quiet && git diff --staged --quiet || git commit -m "Auto-update state files after sync [skip ci]"
          git push
